[project]
name = 'taral-bank-mvp'
description = 'Taral MVP bank contracts'
authors = ["Taral team"]
telemetry = false
cache_dir = 'contracts/external'
boot_contracts = ["pox", "costs-v2"]

[contracts.trait-ownable]
path = 'contracts/trait-ownable.clar'
clarity_version = 2
epoch = 2.4

[contracts.trait-sip-010]
path = 'contracts/trait-sip-010.clar'
clarity_version = 2
epoch = 2.4

[contracts.token-susdt]
path = 'contracts/token-susdt.clar'
clarity_version = 2
epoch = 2.4

[contracts.taral-bank-storage]
path = 'contracts/taral-bank-storage.clar'
clarity_version = 2
epoch = 2.4

[contracts.taral-bank]
path = 'contracts/taral-bank.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
