[project]
name = 'taral-bank-mvp'
description = 'Taral MVP bank contracts'
authors = ["Taral team"]
telemetry = false
cache_dir = 'cache'
boot_contracts = ["pox", "costs-v2"]

[[project.requirements]]
contract_id = "SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-susdt"

[contracts.taral-bank-storage]
path = 'contracts/taral-bank-storage.clar'
clarity_version = 2
epoch = 2.4

[contracts.taral-bank]
path = 'contracts/taral-bank.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
